import os

FPS = 60
SCALE = 4
ONE_SECOND = 1000
FADE_MS = 1000
HD_RESOLUTION = (1920, 1080)
DEFAULT_VOLUME = 0.5
MUSIC_VOLUME = 0.6
SFX_VOLUME = 0.8

SCORE_SCALING = 1.0
SCORE_SCALING_INCREASE = 1.25
SCORE_BASE = 4000

TRAIT_CARD_SIZE = 260

HEADER_FLOAT = 0.002
SPRITE_FLOAT = 0.0025
SHIP_SELECTION_OFFSET = 200
FLIGHT_SPEED = 16

SAVE_DIR_NAME = ".astros"
CONFIG_FILE = "config.json"
SCREENSHOTS_DIR = os.path.join(SAVE_DIR_NAME, "imgs")
INDENTS = 4

INPUT_CONTROLLER = "controller"
INPUT_MOUSE = "mouse"

BACKGROUND = (16, 19, 31)

COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 100, 255)
COLOR_SMOKE = (100, 100, 100)

COLOR_LIGHT_RED = (255, 50, 50)
COLOR_LIGHT_ORANGE = (255, 200, 0)
COLOR_LIGHT_YELLOW = (255, 255, 100)

INPUT_NAV_COOLDOWN = 150

SCREEN_SHAKE = 30

CRT_CURVATURE = 0.5

BASE_RUMBLE_MS = 50
HIGH_RUMBLE_MS = 1000

HUD_PADDING = 80
FONT_DEFAULT_SIZE = 24
FONT_MEDIUM_SIZE = 36

TITLE_Y = 200
TITLE_OFFSET = 600

STAT_Y_OFFSET = 40

SKILL_TAB_Y = 200
SKILL_TAB_OFFSETS = (60, 20)
SKILL_TAB_PADDING = 40
SKTAB_HEADER_OFFSET = 300
SKILL_TAB_GRID = [(250, 200), (350, 200), (450, 200)]
ALPHA = 120

CROSSHAIRS = 10

INTERFACE_HITPOINTS = (40, 40)

INTERFACE_SHIELD = (40, 17)
INTERFACE_SHIELD_COLS = 33
INTERFACE_SHIELD_OFFSET = (0, -150)

INTERFACE_OVERHEAT = (273, 233)
INTERFACE_OVERHEAT_WIDTH = 20
INTERFACE_OVERHEAT_HEIGHT = 145

INTERFACE_GUNS = (32, 32)
INTERFACE_GUNS_COLS = 4
INTERFACE_GUNS_OFFSET = (-210, -20)

INTERFACE_XP = (40, 17)
INTERFACE_XP_COLS = 33
INTERFACE_XP_OFFSET = (0, -175)

SETTINGS_X_OFFSET, SETTINGS_Y_OFFSET = SKTAB_HEADER_OFFSET + 50, 50
SETTINGS_COL_OFFSET = 200
SETTINGS_LINESPACE = 50
SETTINGS_SETTING_GAP = 50
SETTINGS_VOLUME_WIDTH = 200
SETTINGS_VOLUME_HEIGHT = 20

PAUSED_TEXT_Y = 150
TEXT_PADDING = 10
LINE_SPACING = 10
GUN_LABEL_OFFSET = 40

SHIP_MAX_HITPOINTS = 200
SHIP_MAX_SHIELD = 25

SHIP_FRAMES = 9
SHIP_SCALE = 4
SHIP_HITBOX = -0.6
SHIP_OFFSETS = (-25, 200)

SHIP_GUNS = ["beam", "shotgun", "auto", "nuke"]
SHIP_TAGS = {
    gun: f"game.gun.{gun}"
    for gun in SHIP_GUNS
}

SHIP_GUNS_RATES = {
    "beam": 250,
    "shotgun": 400,
    "auto": 150,
    "nuke": 900
}

SHIP_AMMO = {
    "beam": -1,
    "shotgun": 200,
    "auto": 400,
    "nuke": 2
}

SHIP_SHIELD_FRAMES = 33
SHIP_HITPOINTS_FRAMES = 28
SHIP_CRIT_CHANCE_SIZE = 36
SHIP_DAMAGE_SIZE = 24
SHIP_FIRE_RATE = 250
SHIP_IFRAMES = 200
SHIP_VELOCITY = 16
SHIP_BASE_ANGLE = 90

SHIP_BASE_DAMAGE = 4
SHIP_BASE_CRIT_CHANCE = 0.05
SHIP_COMBO_ADDITION = 0.05
SHIP_NERFED_COMBO_ADDITION = 0.025

SHIP_CREDITS_CAP = 50
SHIP_MANIC_BOOST = 5000

SHIP_XP_PER_LEVEL = 256
SHIP_XP_GROWTH = 1.4
SHIP_LEVEL_ADDITION = 10

SHIP_SHOTGUN_DAMAGE = 10
SHIP_SHOTGUN_PELLETS = 6
SHIP_SHOTGUN_SPREAD = 30
SHIP_NUKE_DAMAGE = 50

SHIP_OVERHEAT_CAP = 2000
SHIP_OVERHEAT_COOLDOWN = 4000
SHIP_OVERHEAT_RATE = 100

SHIP_AUTO_BULLETS = 3
SHIP_AUTO_SPREAD = 5

LEVEL_CAP = 30

FULL_360 = 360

ALIEN_COLORS = {'red': 5, 'green': 10, 'yellow': 15, 'purple': 15,
                'pink': 20, 'orange': 20}
ALIEN_INITIAL_DELAY = 2500
ALIEN_WIDTH = 44
ALIEN_HEIGHT = 32
ALIEN_ADVANTAGE = 10

ALIEN_FORMATION = ['block', 'line', 'clutch']
ALIEN_MOVES = ['sideways', 'chaotic']

ELITE_HP_MULT = 2.0
ELITE_DAMAGE_MULT = 1.5
ELITE_SPEED_MULT = 1.1

SPAWN_COOLDOWN = ONE_SECOND

ALIEN_SHOT_TIMER_MS = 200

ALIEN_PHASES = (0, 1, 3)
ALIEN_SPAWN_INTERVAL_RANGE = (4000, 10_000)

HIGH_FIRE_RATE = 150

ASTEROID_PHASES = (2, 4)
ASTEROID_SPAWN_INTERVAL = 600
ASTEROID_SPAWN_COUNT = 6
ASTEROID_HITPOINTS = 8
ASTEROID_SPEED = 8

ASTEROID_POS = (-200, -50)
ASTEROID_MIN_DISTANCE = 40
ASTEROID_OFFSET = 50

BOSS_BASE_SPEED = 16
BOSS_VERTICAL_STEP = 30
BOSS_ADVANTAGE = ALIEN_ADVANTAGE * 2

BOSS_BASE_HITPOINTS = 100
BOSS_BASE_DAMAGE = 100

BOSS_INVISIBLE_START = 0
BOSS_INVISIBLE_DURATION = 2000

BOSS_PHASES = ["phase1", "phase2", "phase3"]

BOSS_COLORS = {
    "red": 100,
    "green": 200,
    "yellow": 300,
    "purple": 800,
    "pink": 1000,
    "orange": 2000
}

BOSS_DAMAGE = 9999

CELESTIAL_SPAWN_INTERVAL = (30_000, 60_000)
CELESTIAL_MIN_DISTANCE = 200

BLACK_HOLE_SPAWN = 120_000

UPGRADE_SPAWN_INTERVAL = 24_000

PARTICLES_AMOUNT = 10

PHASE_ACTIVE = 0
PHASE_CLEANUP = 1
PHASE_TRANSITION = 2

PHASE_START = 0
PHASE_LENGTH = 15_000
PHASE_BUFFER_TIME = 5000
PHASES_TOTAL = 6

PHASES = [f"wave_{i+1}" for i in range(PHASES_TOTAL)]
PHASE_COLORS = ['red', 'green', 'yellow', 'purple', 'pink', 'orange']

PHASE_FADE = 5000

STAR_COUNT = 100
STAR_SPEED = 2
LIGHT_SPEED = 50

SHOCKWAVE_RADIUS = 900
SHOCKWAVE_SPEED = 40

ANIM_COOLDOWN_BASE = 100
ANIM_COOLDOWN_OVERLAY = 50

EXPLOSION_FRAMES = 7
MEGAEXPLOSION_FRAMES = 4

TOGGLE_TUTORIAL = True
TOGGLE_GOD_MODE = False
TOGGLE_INVINCIBLE = TOGGLE_GOD_MODE
TOGGLE_UNLIMITED_AMMO = TOGGLE_GOD_MODE
TOGGLE_LEVEL_CAP = False

SETTINGS_DEFINITION = [
    {
        "key": "music_volume",
        "label": "game.settings.music",
        "type": "slider",
        "min": 0.0,
        "max": 1.0,
        "step": 0.1,
        "target": "mixer"
    },
    {
        "key": "sfx_volume",
        "label": "game.settings.sfx",
        "type": "slider",
        "min": 0.0,
        "max": 1.0,
        "step": 0.1,
        "target": "mixer"
    },
    {
        "key": "can_screen_shake",
        "label": "game.settings.screen_shake",
        "type": "toggle",
        "target": "state"
    },
    {
        "key": "can_rumble",
        "label": "game.settings.rumble",
        "type": "toggle",
        "target": "state"
    },
    {
        "key": "can_show_controls",
        "label": "game.settings.controls",
        "type": "toggle",
        "target": "state"
    },
    {
        "key": "can_show_hud",
        "label": "game.settings.hud",
        "type": "toggle",
        "target": "state"
    },
    {
        "key": "current_lang",
        "label": "game.settings.lang",
        "type": "lang",
        "target": "state"
    }
]